# f = open("nihao.docx" , "w")
# f.write("hello word")
# cont = f.readline()
# print(cont)
# f.close()


# f = open("file.txt" , "w+")
# f.write("hello world")
# f.close()
# w = open("file.txt" )
# count = w.readline()
# co = w.read()
# w.close()
# print(count)
# print(co)
# w.close()


a = open("file.txt")
cdode = a.readline()
print(cdode)
cdode = a.readline()
print(cdode)
cdode = a.readline()
print(cdode)
cdode = a.readline()
print(cdode)
cdode = a.readline()
print(cdode)
cdode = a.readline()
print(cdode)
a.close()
