# print(help())
# print(help(print))
name_list = ['Tom', 'Jerry', 'Mike']
print(name_list)
name_list.index('Jerry' , 0, 2)
print(name_list)
print(name_list.index('Jerry'))
print(name_list.count('Mike'))
name_list.insert(2, 'mali')
print(name_list)
name_list.remove('Mike')
print(name_list)
name_list.pop(1)
print(name_list)
